openapi: 3.0.0
info:
  version: 1.0.0
  title: Sample API
  description: >-
    A sample API that uses a sample-site as an example to demonstrate features in
    the OpenAPI 3.0 specification
servers:
  - url: 'http://localhost:8003'
paths:
  /test:
    get:
      description: 'test'
  responses:
    '200':
      description: "OK"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responses.yml#/ok'

components:
  schemas:
    message:
      type: string
      example: 登録しました。
